# Generated by Django 4.1.6 on 2023-05-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_remove_box_ordered_remove_box_ordered_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
