# Generated by Django 4.1.6 on 2023-05-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_box_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='ordered_date',
        ),
        migrations.AddField(
            model_name='box',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
