# Generated by Django 4.1.6 on 2023-06-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_rename_picture_product_portrait'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='portrait',
            new_name='image',
        ),
    ]
